version: '2'
services:
  server:
    environment:
      - 'POSTGRES_HOST=postgres'
      - 'POSTGRES_PORT=5432'
      - 'PORT=8080'
    image: 'senpaiplz/hashtagcoolrepo:55a460e5c995cd9b185b85f8dfe19925ba01e746'
    ports:
      - '80:8080'
    links:
      - 'postgres'
  postgres:
    image: 'postgres'
    environment:
      - 'POSTGRES_PASSWORD=mysecretpassword'
      - 'POSTGRES_USER=postgres'
    expose:
      - '5432'
